project:
  type: website
  # output-dir: docs


website:
  title: "MÄTLIK LAB"
  description: "Laboratory of Neuroepigenetics"
  site-url: https://kmatlik.github.io/matlik-lab
  #repo-url: https://github.com/kmatlik/matlik-lab
  # favicon: logo.png
  twitter-card: false
  #   creator: "@handle"
  #   site: "@handle"
  open-graph: true
  # google-analytics:
  #   tracking-id: "UA-XXXXXXXX"
  #   anonymize-ip: true
  # cookie-consent: true


  navbar:
    background: "#030502"
    right:
      - href: index.qmd
        text: HOME
      - Research.qmd
      - Publications.qmd
      - People.qmd
      - Contact.qmd


  page-footer:
    background: light
    right: "Made with Quarto. Figures created with BioRender.com"

enable_google_verification: true
google_site_verification: 9xhBFo87R8VeryGLxbYmSXnLOWJKK1FniRXbDOdBrrA

format:
  html:
    theme: journal #other nice alternatives include journal, united, minty, lumen, yeti, spacelab https://quarto.org/docs/output-formats/html-themes.html
    css: styles.css
    toc: false

execute:
  freeze: auto  # re-render only when source changes



